services:
  database:
    container_name: 'ticket_db'
    image: 'mysql:latest'
    env_file: ./.env
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
    ports:
      - '33306:3306'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - ticket-data:/var/lib/mysql
  app:
    depends_on:
      database:
        condition: service_healthy
    container_name: 'ticket_app'
    image: 'ticket'
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:mysql://$MYSQL_DATABASE:3306/$MYSQL_DATABASE?createDatabaseIfNotExist=true",
             "spring.datasource.username" : "$MYSQL_USER",
             "spring.datasource.password" : "$MYSQL_PASSWORD"
         }'
    ports:
      - '8081:8080'
    restart: unless-stopped
volumes:
  ticket-data: