version: '3.8'

services:
  database:
    container_name: 'ticket_db'
    image: 'mysql:latest'
    env_file: ./.env
    environment:
      - 'MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD'
    ports:
      - '${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}'
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 8s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    volumes:
      - ticket-data:/var/lib/mysql
  app:
    depends_on:
      database:
        condition: service_healthy
    container_name: 'ticket_app'
    image: 'ticket'
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:mysql://ticket_db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?createDatabaseIfNotExist=true",
             "spring.datasource.username" : "$MYSQL_USER",
             "spring.datasource.password" : "$MYSQL_PASSWORD"
         }'
    ports:
      - '${APP_LOCAL_PORT}:${APP_DOCKER_PORT}'
    restart: unless-stopped
volumes:
  ticket-data:
